spring.application.name=logistics
spring.datasource.url=jdbc:mysql://localhost:3308/logistics_db
spring.datasource.username=root
spring.datasource.password=super3

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
